### ISSUE TITLE
Backward jumping bug

### ISSUE THREAD

**Issue by djolapatata** [Karsonic/Checkers-Frontend#5]
Non-king pieces can initiate a backward take if a square behind them is open and would work as a jump if kinged, however you cannot move but when moving that piece to a legal square it will still take the piece as if you had jumped backward and then moved your piece magically to the new location, this causes each player's board to become unsynced and will crash the app on one side

**Comment by krosn** [comment]
fixed in [commit](https://github.com/Karsonic/Checkers-Frontend/commit/1fe356627fbfb3f9520eb0fde088857a453b7836)
